application: ngudanchamcom
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/admin
  static_dir: django/contrib/admin/static/admin
  expiration: '0'

- url: /static/
  static_dir: static

- url: /tinymce/.*
  #script: google.appengine.ext.tinymce
  script: google.appengine.ext.tinymce.zip

- url: /mce_filebrowser/.*
  #script: google.appengine.ext.mce_filebrowser
  script: google.appengine.ext.mce_filebrowser.zip

- url: /.*
  script: djangoappengine.main.application

pagespeed:
  domains_to_rewrite:
  - www.ngudan.com
  enabled_rewriters:
  - MinifyCss
